const MovieActionTypes = {
  FETCH_MOVIE_LIST_START: 'FETCH_MOVIE_LIST_START',
  FETCH_MOVIE_LIST_SUCCESS: 'FETCH_MOVIE_LIST_SUCCESS',
  FETCH_MOVIE_LIST_FAILURE: 'FETCH_MOVIE_LIST_FAILURE',
  ADD_TO_NOMINATED_MOVIE_LIST_START: 'ADD_TO_NOMINATED_MOVIE_LIST_START',
  ADD_TO_NOMINATED_MOVIE_LIST_SUCCESS: 'ADD_TO_NOMINATED_MOVIE_LIST_SUCCESS',
  ADD_TO_NOMINATED_MOVIE_LIST_FAILURE: 'ADD_TO_NOMINATED_MOVIE_LIST_FAILURE',
  REMOVE_FROM_NOMINATED_MOVIE_LIST_START:
    'REMOVE_FROM_NOMINATED_MOVIE_LIST_START',
  REMOVE_FROM_NOMINATED_MOVIE_LIST_SUCCESS:
    'REMOVE_FROM_NOMINATED_MOVIE_LIST_SUCCESS',
  REMOVE_FROM_NOMINATED_MOVIE_LIST_FAILURE:
    'REMOVE_FROM_NOMINATED_MOVIE_LIST_FAILURE',
  EMPTY_MOVIE_LIST: 'EMPTY_MOVIE_LIST',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default MovieActionTypes;
